export const ERROR_CODES = {
  SYSTEM: {
    INTERNAL_SERVER_ERROR: 'SYS001',
  },
  VALIDATION: {
    REQUEST_FAILED: 'VAL001',
    INTERNAL_ERROR: 'VAL002',
    RESPONSE_FAILED: 'VAL003',
  },
  RATE_LIMIT: {
    EXCEEDED: 'RL001',
    RESET_KEY_MISSING: 'RL002',
    RESET_FAILED: 'RL003',
  },
  RULES: {
    UPSERT_FAILED: 'RULE001',
    NOT_FOUND: 'RULE002',
    DELETE_FAILED: 'RULE003',
  },
  AUTH: {
    DEMO_DISABLED: 'AUTH001',
    INVALID_CREDENTIALS: 'AUTH002',
    LOGIN_FAILED: 'AUTH003',
  },
  METRICS: {
    DISABLED: 'MET001',
    RENDER_FAILED: 'MET002',
    EXPORT_FAILED: 'MET003',
  },
  STATS: {
    READ_FAILED: 'STAT001',
  },
  PERFORMANCE: {
    READ_FAILED: 'PERF001',
    ENDPOINT_MISSING: 'PERF002',
    ENDPOINT_NOT_FOUND: 'PERF003',
  },
  API_KEYS: {
    GENERATION_FAILED: 'AK001',
    USER_ID_REQUIRED: 'AK002',
    LIST_FAILED: 'AK003',
    NOT_FOUND: 'AK004',
    LOOKUP_FAILED: 'AK005',
    REVOKE_FAILED: 'AK006',
    ROTATION_FAILED: 'AK007',
    USAGE_FAILED: 'AK008',
  },
} as const;
